### ISSUE TITLE
Website meldet "unerwarteten Fehler" bei Verwendung des Checkers.

### ISSUE THREAD

**Issue by SimonK97** [marcoklein/impftermin#15]
Gestern Abend lief noch alles reibungslos, heute morgen meldet die Website einen "unerwarteten Fehler" nachdem der Code eingegeben wird. Geht man manuell vor erscheint diese Fehlermeldung nicht.
Das Skript timet nach 30000 ms aus und springt zum nächsten Eintrag.

**Comment by marcoklein** [comment]
Hi, hast du das Skript über Nacht laufen gelassen oder war es ein neuer Start?
Welches updateInterval hast du in deiner config.json definiert?
Welche Logs siehst du in der Konsole?
Hast du vielleicht einen Screenshot und idealerweise den HTML Code der Webseite? (Bitte deinen Impfcode anonymisieren)

**Comment by SimonK97** [comment]
Hi, 
hab es nicht über Nacht laufen lassen. Als Intervall habe ich 3 Minuten angegeben. In der Konsole kam nur, dass es zum Timeout kommt, da er die passende Form nicht findet (da nicht weitergeleitet wird). 

Screenshot hab ich jetzt nicht mehr, da es inzwischen wieder geht. Ich habe einfach per VPN meine IP geändert. Jetzt geht es wieder.

**Comment by marcoklein** [comment]
Danke für die Info. Falls es wieder vorkommt kannst du das Intevall verlängern, da der Checker sonst schneller als Bot eingestuft wird.

**Comment by BreitbandModem** [comment]
Hatte den Fehler heute auch. Siehe Screenshot.
Konsolenausgabe:
`impftermin:zentrum Error during retrieval TimeoutError: Navigation timeout of 30000 ms exceeded +37s`

Intervall war auf 0 gesetzt. **Nachdem ich auf 5min verlaengert habe kam der Fehler erst seltener, und dann gar nicht mehr.**

![Fehlermeldung](https://user-images.githubusercontent.com/10243455/120545378-de0da100-c3ee-11eb-9004-a62e1b58a12b.PNG)
