### ISSUE TITLE
[BUG] Not working on MacOS

### ISSUE THREAD

**Issue by nilskasseckert** [marcoklein/impftermin#16]
Hi,

the program is not working on MacOS. If I download it, is has no File-Extension. The file extension ".app" and ".pkg" does not work.

What is the correct extension and way to execute it?

Regards,
Nils

**Comment by quinn-dev** [comment]
Hi Nils,

what happens if you double-click the file? Do you get an error? Does it open in a text editor?

What should work: Try opening a Terminal in the directory where you downloaded "impftermin-macos" and run `./impftermin-macos`.

**Comment by nilskasseckert** [comment]
Hi @quinn-dev ,

yes the text editor opens after I accept that I want to execute software from a non secure developer.

I will try to run it via Terminal.

**Comment by marcoklein** [comment]
Would also be interested how you run it. We might need a section in the readme for that then..

**Comment by nilskasseckert** [comment]
With terminal this also does not work. 

Without sudo:
`./impftermin-macos
zsh: permission denied: ./impftermin-macos
`

With sudo:
`sudo: ./impftermin-macos: command not found`

**Comment by marcoklein** [comment]
Could you try adding execution rights with `chmod +x ./impftermin-macos`?

**Comment by nilskasseckert** [comment]
Thank you, I totally forgot. But if I start the program the following error occurs. The empty config file was created.
<img width="888" alt="Bildschirmfoto 2021-05-08 um 07 24 56" src="https://user-images.githubusercontent.com/3728238/117527736-7f5f2e00-afce-11eb-99d7-5dcd11b9377b.png">

Manual config creation works. Thanks!

**Comment by quinn-dev** [comment]
> Thank you, I totally forgot. But if I start the program the following error occurs. The empty config file was created.

What version have you downloaded? Every version since [1.3.0](https://github.com/marcoklein/impftermin/releases/tag/1.3.0) features an interactive CLI to generate the config file.

**Comment by marcoklein** [comment]
PR #21 adds instructions on how to run the application on linux and mac.
