### ISSUE TITLE
Wrong reporting of  "Appointments available"

### ISSUE THREAD

**Issue by FrankReisenhofer** [marcoklein/impftermin#18]
Very often the tool is reporting:

 Appointments available!!
 
 But instead I see

![image](https://user-images.githubusercontent.com/37330222/117465500-1043f400-af52-11eb-881f-cc290128abd6.png)

The reason is that the search takes a while. So please consider a waiting time when checking for appointments in this screen

**Comment by FrankReisenhofer** [comment]
One hint: During your check the following window is visible:
![image](https://user-images.githubusercontent.com/37330222/117478082-007edc80-af5f-11eb-8626-eecc3f26ad05.png)

**Comment by marcoklein** [comment]
Thanks for reporting. I increased the default wait time to 20s.
