### ISSUE TITLE
Invalid configuration: StructError: At path: queue.0.url -- Expected a value of type `ImpfterminURL

### ISSUE THREAD

**Issue by FrankReisenhofer** [marcoklein/impftermin#25]
Since version 1.5.0 I can't start the windows executable. It is throwing the validation error:

impftermin:config Invalid configuration: StructError: At path: queue.0.url -- Expected a value of type `ImpfterminURL`, but received: `"https://002-iz.impfterminservice.de/impftermine/service?plz=69124"`

According to my understanding the provided URL is correct.

Any idea why the error is been thrown?

**Comment by maximilianfink** [comment]
I have the same problem. it shows me "please enter a valid value" on startup after entering the url

**Comment by marcoklein** [comment]
Yes, the validation was testing for a `www.impfterminservice.de`. I changed it to `impfterminservice.de`. Thanks for reporting :)

**Comment by FrankReisenhofer** [comment]
@marcoklein : Unfortunately the issue still exists. The correct code should be:

return isUrl(url) && new URL(url).host.match("[^.]+\\.impfterminservice\\.de")!=null;
 
 in configuration.ts (Line 28) :-). I failed to create a PR due to missing permissions.

**Comment by marcoklein** [comment]
I released your fix - could you retest? I am leaving this ticket open for now.

**Comment by maximilianfink** [comment]
yes works, by the way also super on Mac OS, I have tested:) thank you!!!
