### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by mkoderer** [marcoklein/impftermin#29]
@marcoklein  could you add a License file to your code?
I would like to contribute a bug fix but it's tricky if it's not released as open source..

**Comment by mkoderer** [comment]
Just for reference: https://docs.github.com/en/enterprise-server@3.0/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by marcoklein** [comment]
Good that you reminded me of that one 👍

**Comment by mkoderer** [comment]
Thx
