### ISSUE TITLE
False positive appointment if "termine" screen is too slow

### ISSUE THREAD

**Issue by mkoderer** [marcoklein/impftermin#30]
In case the Termine screen is still building up it if statement [1] wrongly matches.

Currently the system seems to be very slow. This is the reason this state could take some seconds:
![image](https://user-images.githubusercontent.com/4669365/118173227-97e7a200-b42d-11eb-87bd-d3c691d12e65.png)

[1]: https://github.com/marcoklein/impftermin/blob/master/src/appointments.ts#L119

**Comment by mkoderer** [comment]
I have a fix for this but I would need to get issues/29 resolved first.

**Comment by marcel757** [comment]
Bug is still not fixed!

**Comment by mkoderer** [comment]
Hi @marcoklein, I really believe the logic is incorrect.
It should be logical AND and not OR.
I pushed my latest changes here:
https://github.com/mkoderer/impftermin/commit/004f7b3afcc04175960d33415d449d11d2a162a6

This worked for me at least.. but testing this is really tricky these days.

**Comment by marcoklein** [comment]
Okay, then I am reopening this issue. I thought the logic worked for me.. Maybe the website has changed?

**Comment by marcoklein** [comment]
Thanks for your proposed change.. As you say it is hard to test - but looks better with the adjusted logic. I can't test it cause I got no code but I left the debug statements in place. Please let me know if this works now.

**Comment by mkoderer** [comment]
Thanks - I hope someone could attach the debug log in case of a hit.

**Comment by Whindu** [comment]
With code the output looks like this:

impftermin:zentrum Performing a check for location with url https://xxx-iz.impfterminservice.de/impftermine/service?plz=xxxxx +30s
  impftermin:appointments Checking impf location https://xxx-iz.impfterminservice.de/impftermine/service?plz=xxxxx +267ms
  impftermin:appointments We are no longer in the waiting room +673ms
  impftermin:appointments Checking with existing code xxxx-xxxx-xxxx +1s
  impftermin:appointments No appointments +28s
  impftermin:appointments DEBUG: appointmentText=  Derzeit stehen leider keine Termine zur Verfügung.

Die Impfzentren stellen regelmäßig neue Termine ein. Bitte prüfen Sie zu einem späteren Zeitpunkt mit Hilfe Ihres Vermittlungscodes, ob wieder Termine zur Verfügung stehen. +0ms

**Comment by Whindu** [comment]
With code but too slow web site and wrong assumption an appointment would be available:

impftermin:appointments Checking impf location https://xxx-iz.impfterminservice.de/impftermine/service?plz=xxxxx +378ms
impftermin:appointments We are no longer in the waiting room +6s
impftermin:appointments Checking with existing code xxxx-xxxx-xxxx +1s
impftermin:appointments Appointments available!! +33s
impftermin:appointments DEBUG: appointmentText=undefined +0ms

**Comment by mkoderer** [comment]
Thanks @Whindu. Have you captured the HTML source by any chance?
I saw this "undefined" appointmentText also for a valid hit.
So better to have a false alert than a missed hit..

@marcoklein unfortunately I would suggest to open the issue again.

**Comment by Whindu** [comment]
No, only the log output.

**Comment by mhl66** [comment]
Sorry, there seems to be no reproducible cause (whether the browser window is "slow" or anything). It is **very annoying to wake up in the middle of the night**.

**Comment by mkoderer** [comment]
The real annoying thing is that the impfterminservice is absolutely unusable and unreliable these days.
For me it worked over night - could be related to the load of the service.

I tried to debug it today but had no success. I think we need to add more logging to find the root cause.

**Comment by marcoklein** [comment]
I currently see no effective way of avoiding false positives.. One way might be to check if the 'actual' appointments available page shows up. However, I do not have the HTML for this to implement the necessary steps. The risk with this is also that the impfterminservice.de site changes and you would get false negatives then (so you never get notified).

From my experience the tool yields a couple of appointments (also with code) during the day - however, this highly depends on the locations you choose. I am leaving this open for further discussions but see no effective fix for now.

**Comment by mkoderer** [comment]
@marcoklein what we could do is log the full html in case of appointmentText == undef.
With that it would be easier to adapt the logic.

**Comment by marcoklein** [comment]
Yes that would be an option. I'll look into this if I find time but feel free to implement the log change.
