### ISSUE TITLE
Many Thanks for developing this tool!

### ISSUE THREAD

**Issue by FrankReisenhofer** [marcoklein/impftermin#35]
Dear Mr. @marcoklein ,

As I found no other way to contact you as you did not provide an e-mail in your profile :-):

Many, many thanks for developing this tool. It helped me to find an appointment.

Thanks for spending the time and effort and sharing it to us!

All the best for you.

Best Regards

Frank Reisenhofer

**Comment by marcoklein** [comment]
Thank you very much @FrankReisenhofer. I appreciate this and I am glad that this tool helps people :)
