### ISSUE TITLE
MacOS Bug / EOF

### ISSUE THREAD

**Issue by JoLaeng** [marcoklein/impftermin#36]
Hi,
I ran into the issue after chmodx-ing and starting the app. The issue occured directly after inserting the URLs and after the app tried to download bromium:

 impftermin:main Downloading Chromium... +5m
(node:2962) UnhandledPromiseRejectionWarning: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
(node:2962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by marcoklein** [comment]
Seems to be an open bug in puppeteer. I only found this discussion: https://github.com/opstrace/opstrace/issues/275#issuecomment-833468408 

You could try deleting the `.local-chromium` folder from your temporary directory. Then the app will re-trigger the download.
This is the code snippet where the download happens: https://github.com/marcoklein/impftermin/blob/master/src/index.ts#L22

**Comment by marcoklein** [comment]
Closing this as it should be fixed by the latest chromium.
