### ISSUE TITLE
False positive if the "no free appointments" message takes longer than 20s to load

### ISSUE THREAD

**Issue by patrick246** [marcoklein/impftermin#42]
This issue is like #30, but for the case without a code yet.

https://github.com/marcoklein/impftermin/blob/065b21197e0de5ff9682668ad5206c6f978ae306/src/appointments.ts#L150

The timeout in this line is 20s, I think this could be modified to watch for the loading circle to be gone. I can investigate this further after work. Now that there is no prioritization anymore, the servers seem to be responding slower.

**Comment by marcoklein** [comment]
Hi @patrick246, thanks for the report - yes, a positive check would be better, however I do not have the appropriate HTML files to adjust the scraper. Feel free to look into this and propose a change.
