### ISSUE TITLE
Website has a white screen/Won't open

### ISSUE THREAD

**Issue by SzudemARAH** [marcoklein/impftermin#47]
When a friend of mine is starting the Programm the website is opening but its only white screen. It is happening with Edge and Chrome Browser and also on different PCs. How to fix that? 
And on my browser the Programm won't start at all.. It worked for a few times but even after a reinstall it is not opening anymore :/
This programm was so helpful to get an appointment! I hope we get it to work again.

**Comment by marcoklein** [comment]
Hi @SzudemARAH, could you try deleting the Chromium installation from the temporary folder like in https://github.com/marcoklein/impftermin/issues/37?

Other then that: the bot fetches a local Chormium version and doesn't use already installed browsers. When starting you should see a terminal popping up - is there anything specific written?
