### ISSUE TITLE
[Feature] Add option to check availability for a certain age

### ISSUE THREAD

**Issue by quinn-dev** [marcoklein/impftermin#6]
After checking for appointments without a code and confirming your entitlement to vaccination, you are asked to enter your age. If only AstraZeneca is available and you are under the age of 60, the same error message will be shown as when no appointments are available:

![no-appointments](https://user-images.githubusercontent.com/78063175/117314611-78250c80-ae76-11eb-99fe-106bb9d8219e.png)

To further automate this process, the tool should enter the user's age into the form's field and only make a sound if appointments for the user are actually available. This could be achieved by specifying an "age" property in `config.json`.

Here's how the entire page looks like:
![form](https://user-images.githubusercontent.com/78063175/117313237-3d6ea480-ae75-11eb-9476-662d737082c8.png)

I uploaded the corresponding HTML of the webpage [as a gist](https://gist.github.com/quinn-dev/42494a625c5e8cd18a94a657ae08e489).

I also intend to look into this further myself if my time allows it.

**Comment by marcoklein** [comment]
Would be quite interesting to add some further steps. You could add these steps [here](https://github.com/marcoklein/impftermin/blob/master/src/appointments.ts#L125). If the `config.json` defines an age attribute you could insert that here, press the button, and then check if you get the warning box. This will be easy to implement but hard to test.
