### ISSUE TITLE
[Bug] Plays sound when internet connection gets lost

### ISSUE THREAD

**Issue by quinn-dev** [marcoklein/impftermin#7]
When I'm in the waiting room and the internet connection gets lost, the program outputs "Appointments available!!" and plays the sound as soon as the waiting room page reloads and Chrome shows the "No internet" page.

**Comment by marcoklein** [comment]
Thanks for submitting this bug.

I found an example about tracking the online state change [here](https://github.com/puppeteer/examples/blob/master/monitor_internet_connection.js).

I think the best approach is to check if we are "really" connected before returning from the [checkAppointments](https://github.com/marcoklein/impftermin/blob/master/src/appointments.ts#L151) function. This would the only return true if we also have an open connection.

The alternative would be some overall application interrupt in the main loop. That would kill the bot until we are back online.

I'll have a look into the actual fix if I find some time.
